version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'notes'
      POSTGRES_USER: 'Kederly'
      POSTGRES_PASSWORD: 'Qwerty123'

  backend:
    build: ./backend
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
        python manage.py migrate &&
        gunicorn config.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production

  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on:
      - nginx


