# Generated by Django 4.1 on 2022-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Пользователь не активен'),
        ),
    ]
