# Generated by Django 4.1 on 2022-08-24 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0002_todo_note_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_users',
        ),
        migrations.AddField(
            model_name='project',
            name='project_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
