# Generated by Django 4.1 on 2022-08-24 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0003_remove_project_project_users_project_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_users',
        ),
        migrations.AddField(
            model_name='project',
            name='project_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
